
spring:

  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.52.138:3306/vueblog?serverTimezone=UTC
    username: root
    password: cjcisgood
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 192.168.52.138:6379
